### ISSUE TITLE
Missing ENUM: LayoutMode

### ISSUE THREAD

**Issue by GeorgeS2019** [RhubarbVR/LibGodotSharp#2]
<img src="https://user-images.githubusercontent.com/49812372/219968302-687705da-58b7-4224-a160-de31f2e48990.png" width=200px>

![image](https://user-images.githubusercontent.com/49812372/219968342-5627bc44-1bc4-43d2-9699-5c2e1a69fd36.png)

**Comment by Faolan-Rad** [comment]
So the problem is that there a name collision

**Comment by Faolan-Rad** [comment]
What class is the property in

**Comment by Faolan-Rad** [comment]
Is this preventing you from building or is this a usability problem

**Comment by GeorgeS2019** [comment]
The LayoutMode Enum is defined in exported json but not its elements

Compared to LayoutDirection,  the Variable name referring to LayoutMode needs to be LayoutModeValue

**Comment by Faolan-Rad** [comment]
It should be in the enum folder

**Comment by GeorgeS2019** [comment]
> Is this preventing you from building or is this a usability problem

Yes!  libgodotsharp fails to build

**Comment by Faolan-Rad** [comment]
I
I am in general vc

**Comment by GeorgeS2019** [comment]
![image](https://user-images.githubusercontent.com/49812372/219969130-75de5f1b-d7a9-4b88-a68d-90662041e889.png)

**Comment by GeorgeS2019** [comment]
Needs 2 min

**Comment by Faolan-Rad** [comment]
Okay some big things broke

**Comment by GeorgeS2019** [comment]
```cs
enum LayoutMode : long {
        LAYOUT_MODE_POSITION,
        LAYOUT_MODE_ANCHORS,
        LAYOUT_MODE_CONTAINER,
        LAYOUT_MODE_UNCONTROLLED,
};
```

**Comment by Faolan-Rad** [comment]
should be fixed with https://github.com/RhubarbVR/LibGodotSharp/commit/55d26a04caead9524fab90f20508473f83a863a6

**Comment by GeorgeS2019** [comment]
Just checked the latest commit: 

# Problem remains

<image src="https://user-images.githubusercontent.com/49812372/220658305-eb48562c-7bdd-46aa-a79d-39325e0dc735.png" width=500px>

<image src="https://user-images.githubusercontent.com/49812372/220657710-226994d8-9947-495e-a3f0-0082a055b685.png" width=400px>

**Comment by Faolan-Rad** [comment]
That is correct it falls back to number representation
